services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_ROOT_HOST: '%'
      MARIADB_USER: kolobashek
      MARIADB_PASSWORD: Password123!
      MYSQL_DATABASE: specmash
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    dns:
      - 8.8.8.8
      - 8.8.4.4

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    dns:
      - 8.8.8.8
      - 8.8.4.4

  specmash-server:
    build:
      context: ./packages/specmash-server
      dockerfile: Dockerfile
    container_name: specmash-server
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: kolobashek
      DB_PASSWORD: Password123!
      DB_NAME: specmash
    ports:
      - '3001:3000'
    depends_on:
      mariadb:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4

  specmash-react:
    build:
      context: ./packages/specmash-react
      dockerfile: Dockerfile
    container_name: specmash-react
    ports:
      - '3000:3000'
    depends_on:
      - specmash-server
    dns:
      - 8.8.8.8
      - 8.8.4.4

  specmash-itinerary:
    build:
      context: ./packages/specmash-itinerary
      dockerfile: Dockerfile
    container_name: specmash-itinerary
    ports:
      - '19006:19006'
    depends_on:
      - specmash-server
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  mariadb_data:
